/*Integrantes Equipo 1:
- Ordaz Rangel David
- Hernández Carlos Mayte Eridani
- Torres Pérez Ashley
Semestre: 3     Grupo: 3 
 */
package pck_vista;

import pck_modelo.Prestamo_BD;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;

public class Frm_Prestamo extends javax.swing.JFrame {

    public final Prestamo_BD PBD;

    public Frm_Prestamo() {
        initComponents();
        this.setLocationRelativeTo(null);
        PBD = new Prestamo_BD();
        this.listar();
    }

    public void listar() {
        DTM_Prestamos.setModel(PBD.getDatosPrestamo());
    }

    public void limpiar() {
        idPrestamoT.setText("");
        idPrestamoT.setEnabled(true);
        cuentaAlumno.setText("");
        codigoBarras.setText("");
        idBibliotecario.setText("");
        fechaInicio.setDate(null);
        fechaFin.setDate(null);
        idPrestamoT.requestFocus();
    }

    public void agregarActualizar(boolean agregar) {
        String idPrestamo = null, idBiblio = null;
        int cuentaAlumno = 0, codigoBarras = 0, res = 0;
        Date fechaIni = null, fechaFin = null;
        java.sql.Date fI = null, fF = null;
        boolean valido = true;

        idPrestamo = this.idPrestamoT.getText();
        if (idPrestamo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El ID del Prestamo es un dato requerido.",
                    "CAMPO VACIO!", 2);
            valido = false;
            this.idPrestamoT.requestFocus();
        }

        try {
            cuentaAlumno = Integer.parseInt(this.cuentaAlumno.getText());
            if (cuentaAlumno < 1) {
                JOptionPane.showMessageDialog(null, "El numero de cuenta del alumno no puede ser menor a 1.",
                        "ERROR DE DATOS", 2);
                valido = false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El valor del campo de No. Cuenta es invalido. Inrese un dato numérico", "ERROR DE DATOS", 2);
            valido = false;
            this.cuentaAlumno.setText("");
            this.cuentaAlumno.requestFocus();
        }

        try {
            codigoBarras = Integer.parseInt(this.codigoBarras.getText());
            if (codigoBarras < 1) {
                JOptionPane.showMessageDialog(null, "El codigo del material no puede ser menor a 1.",
                        "ERROR DE DATOS", 2);
                valido = false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El valor del campo de codigo del material es invalido. Ingrese un dato numérico", "ERROR DE DATOS", 2);
            valido = false;
            this.codigoBarras.setText("");
            this.codigoBarras.requestFocus();
        }

        idBiblio = this.idBibliotecario.getText();
        if (idBiblio.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El ID del Bibliotecario es un dato requerido.",
                    "CAMPO VACIO!", 2);
            valido = false;
            this.idBibliotecario.requestFocus();
        }

        fechaIni = fechaInicio.getDate();
        if (fechaIni == null) {
            JOptionPane.showMessageDialog(null, "La Fecha de Inicio de Prestamo es un dato requerido.",
                    "CAMPO VACIO!", 2);
            valido = false;
        } else {
            fI = new java.sql.Date((long) fechaIni.getTime());
        }

        fechaFin = this.fechaFin.getDate();
        if (fechaFin == null) {
            JOptionPane.showMessageDialog(null, "La Fecha de Fin de Prestamo es un dato requerido.",
                    "CAMPO VACIO!", 2);
            valido = false;
        } else {
            fF = new java.sql.Date((long) fechaFin.getTime());
        }
        
        if(agregar && valido){
            res = PBD.agregarRegistroPrestamo(idPrestamo, cuentaAlumno, codigoBarras, idBiblio, fI, fF);
        } else if(!agregar && valido){
            res= PBD.actualizarRegistroPrestamo(idPrestamo, cuentaAlumno, codigoBarras, idBiblio, fI, fF);
        }
        if(res > 0){
            this.listar();
            this.limpiar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idPrestamoT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cuentaAlumno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        codigoBarras = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        idBibliotecario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        limpiarButton = new javax.swing.JButton();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechaFin = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        busquedaParametro = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DTM_Prestamos = new javax.swing.JTable();
        guardarButton = new javax.swing.JButton();
        actualizarButton = new javax.swing.JButton();
        listarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catálogo de Prestamos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 24), new java.awt.Color(102, 0, 0))); // NOI18N

        jLabel1.setText("ID Prestamo:");

        jLabel2.setText("No. Cuenta de Alumno:");

        jLabel3.setText("Codigo Barras:");

        codigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBarrasActionPerformed(evt);
            }
        });

        jLabel4.setText("ID Bibliotecario:");

        jLabel5.setText("Fecha de Inicio de Prestamo:");

        jLabel6.setText("Fecha de Fin de Prestamo:");

        limpiarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clean.png"))); // NOI18N
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idPrestamoT, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuentaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idBibliotecario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(limpiarButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idPrestamoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cuentaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(codigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(idBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(limpiarButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda de Prestamos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(102, 0, 0))); // NOI18N

        jLabel7.setText("ID Prestamo:");

        buscarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        buscarButton.setText("BUSCAR");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(busquedaParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(busquedaParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Prestamos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(102, 0, 0))); // NOI18N

        DTM_Prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        DTM_Prestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DTM_PrestamosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DTM_Prestamos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        guardarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.JPG"))); // NOI18N
        guardarButton.setText("GUARDAR");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        actualizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar1.JPG"))); // NOI18N
        actualizarButton.setText("ACTUALIZAR");
        actualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarButtonActionPerformed(evt);
            }
        });

        listarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.JPG"))); // NOI18N
        listarButton.setText("LISTAR");
        listarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar1.JPG"))); // NOI18N
        eliminarButton.setText("ELIMINAR");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(guardarButton)
                        .addGap(62, 62, 62)
                        .addComponent(actualizarButton)
                        .addGap(60, 60, 60)
                        .addComponent(listarButton)
                        .addGap(59, 59, 59)
                        .addComponent(eliminarButton)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarButton)
                    .addComponent(actualizarButton)
                    .addComponent(listarButton)
                    .addComponent(eliminarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DTM_PrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DTM_PrestamosMouseClicked
        // TODO add your handling code here:
        this.limpiar();
        int fila = DTM_Prestamos.getSelectedRow();
        idPrestamoT.setEnabled(false);
        
        idPrestamoT.setText(DTM_Prestamos.getValueAt(fila, 0).toString());
        cuentaAlumno.setText(DTM_Prestamos.getValueAt(fila, 1).toString());
        codigoBarras.setText(DTM_Prestamos.getValueAt(fila, 2).toString());
        idBibliotecario.setText(DTM_Prestamos.getValueAt(fila, 3).toString());
        String fechaIni = DTM_Prestamos.getValueAt(fila, 4).toString();
        java.util.Date dateI;
        try {
            dateI = new SimpleDateFormat("yyyy-MM-dd").parse(fechaIni);
            fechaInicio.setDate(dateI);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar la fecha de inicio de prestamo.", "ERROR", 2);
        }
        String fechaF = DTM_Prestamos.getValueAt(fila, 5).toString();
        java.util.Date dateF;
        try {
            dateF = new SimpleDateFormat("yyyy-MM-dd").parse(fechaF);
            this.fechaFin.setDate(dateF);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar la fecha de fin de prestamo.", "ERROR", 2);
        }
    }//GEN-LAST:event_DTM_PrestamosMouseClicked

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:
        this.agregarActualizar(true);
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        // TODO add your handling code here:
        this.agregarActualizar(false);
    }//GEN-LAST:event_actualizarButtonActionPerformed

    private void listarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarButtonActionPerformed
        // TODO add your handling code here:
        this.listar();
    }//GEN-LAST:event_listarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        // TODO add your handling code here:
        int res = 0;
        int fila = DTM_Prestamos.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro de la tabla.", "Eliminar un registro.", 2);
        } else {
            res = PBD.eliminarRegistroPrestamo(DTM_Prestamos.getValueAt(fila, 0).toString());
            if (res > 0) {
                this.listar();
                this.limpiar();
            }
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_limpiarButtonActionPerformed

    private void codigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoBarrasActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
        DTM_Prestamos.setModel(PBD.buscarRegistroPrestamo(busquedaParametro.getText()));
    }//GEN-LAST:event_buscarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Prestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DTM_Prestamos;
    private javax.swing.JButton actualizarButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField busquedaParametro;
    private javax.swing.JTextField codigoBarras;
    private javax.swing.JTextField cuentaAlumno;
    private javax.swing.JButton eliminarButton;
    private com.toedter.calendar.JDateChooser fechaFin;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JButton guardarButton;
    private javax.swing.JTextField idBibliotecario;
    private javax.swing.JTextField idPrestamoT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JButton listarButton;
    // End of variables declaration//GEN-END:variables
}
